from __future__ import annotations

from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score, roc_auc_score
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from app.services.risk_engine import FEATURES


ROOT = Path(__file__).resolve().parent
DATA_PATH = ROOT / "data" / "synthetic_transactions.csv"
MODEL_PATH = ROOT / "models" / "risk_model.joblib"


def generate_synthetic_data(n: int = 6000, seed: int = 42) -> pd.DataFrame:
    rng = np.random.default_rng(seed)
    amount = rng.lognormal(mean=8.4, sigma=1.0, size=n).clip(50, 250000)
    hour = rng.integers(0, 24, n)
    frequency = rng.poisson(6, n).clip(0, 80)
    account_age = rng.gamma(shape=2.2, scale=180, size=n).clip(0, 3650).astype(int)
    prev_count = rng.poisson(np.maximum(account_age / 20, 1)).clip(0, 10000)
    failed = rng.poisson(0.35, n).clip(0, 20)
    location = rng.binomial(1, 0.08, n)
    device = rng.binomial(1, 0.12, n)
    intl = rng.binomial(1, 0.10, n)
    unusual = rng.binomial(1, 0.09, n)

    risk_logit = (
        -4.2
        + (amount > 30000) * 0.75
        + (amount > 75000) * 1.05
        + (frequency > 14) * 1.0
        + (frequency > 24) * 0.8
        + (hour <= 5) * 0.75
        + location * 1.45
        + device * 1.15
        + (account_age < 14) * 1.25
        + (prev_count < 3) * 0.65
        + (failed >= 2) * 0.8
        + (failed >= 4) * 1.15
        + intl * 0.8
        + unusual * 1.4
    )
    fraud_probability = 1 / (1 + np.exp(-risk_logit))
    fraud = rng.binomial(1, fraud_probability)

    df = pd.DataFrame(
        {
            "amount": amount.round(2),
            "transaction_frequency": frequency,
            "transaction_hour": hour,
            "location_mismatch": location,
            "device_change": device,
            "account_age_days": account_age,
            "previous_transaction_count": prev_count,
            "failed_transaction_count": failed,
            "international_transaction": intl,
            "unusual_transaction": unusual,
            "is_fraud": fraud,
        }
    )
    return df


def train() -> dict:
    ROOT.joinpath("data").mkdir(exist_ok=True)
    ROOT.joinpath("models").mkdir(exist_ok=True)
    df = generate_synthetic_data()
    df.to_csv(DATA_PATH, index=False)

    x_train, x_test, y_train, y_test = train_test_split(
        df[FEATURES], df["is_fraud"], test_size=0.25, random_state=42, stratify=df["is_fraud"]
    )
    candidates = {
        "logistic_regression": Pipeline(
            [
                ("scale", StandardScaler()),
                ("model", LogisticRegression(max_iter=1000, class_weight="balanced", solver="liblinear")),
            ]
        ),
        "random_forest": RandomForestClassifier(
            n_estimators=180, min_samples_leaf=8, class_weight="balanced", random_state=42, n_jobs=1
        ),
    }
    scores = {}
    thresholds = np.linspace(0.05, 0.75, 71)
    best_name = ""
    best_model = None
    best_score = -1.0
    best_threshold = 0.5
    for name, model in candidates.items():
        model.fit(x_train, y_train)
        probability = model.predict_proba(x_test)[:, 1]
        threshold_scores = [(threshold, f1_score(y_test, (probability >= threshold).astype(int))) for threshold in thresholds]
        threshold, model_f1 = max(threshold_scores, key=lambda item: item[1])
        prediction = (probability >= threshold).astype(int)
        scores[name] = {
            "threshold": round(float(threshold), 2),
            "f1": round(float(model_f1), 4),
            "roc_auc": round(float(roc_auc_score(y_test, probability)), 4),
        }
        if scores[name]["f1"] > best_score:
            best_score = scores[name]["f1"]
            best_name = name
            best_model = model
            best_threshold = float(threshold)

    joblib.dump(
        {
            "model": best_model,
            "features": FEATURES,
            "model_name": best_name,
            "model_version": "risklens-synthetic-v1",
            "decision_threshold": best_threshold,
            "candidate_scores": scores,
            "dataset": "Synthetic transaction data generated by backend/train.py",
        },
        MODEL_PATH,
    )
    print(f"Saved {best_name} model to {MODEL_PATH}")
    print(scores)
    return scores


if __name__ == "__main__":
    train()
